twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_horizontal_layout.html.twig'
    globals:
        sf_version: '%app.sf_version%'

when@test:
    twig:
        strict_variables: true
